21:50:34 - [36mINFO [0m hdbg.py init_logger:1013                               21:50:34 - [36mINFO [0m hdbg.py init_logger:1013                               Saving log to file '{'/app/dev_scripts_helpers/documentation/notes_to_pdf.py.log'}'
21:50:34 - [36mINFO [0m hdbg.py init_logger:1018                               21:50:34 - [36mINFO [0m hdbg.py init_logger:1018                               > cmd='/app/dev_scripts_helpers/documentation/notes_to_pdf.py --input /app/dev_scripts_helpers/documentation/test/outcomes/Test_notes_to_pdf1.test3/tmp.scratch/input.md --type pdf --script /app/dev_scripts_helpers/documentation/test/outcomes/Test_notes_to_pdf1.test3/tmp.scratch/script.sh --output /app/dev_scripts_helpers/documentation/test/outcomes/Test_notes_to_pdf1.test3/tmp.scratch/output.pdf --filter_by_header Header2'
21:50:34 - [36mINFO [0m notes_to_pdf.py _main:722                              21:50:34 - [36mINFO [0m notes_to_pdf.py _main:722                              cmd line=/app/dev_scripts_helpers/documentation/notes_to_pdf.py --input /app/dev_scripts_helpers/documentation/test/outcomes/Test_notes_to_pdf1.test3/tmp.scratch/input.md --type pdf --script /app/dev_scripts_helpers/documentation/test/outcomes/Test_notes_to_pdf1.test3/tmp.scratch/script.sh --output /app/dev_scripts_helpers/documentation/test/outcomes/Test_notes_to_pdf1.test3/tmp.scratch/output.pdf --filter_by_header Header2
21:50:34 - [36mINFO [0m notes_to_pdf.py _run_all:525                           21:50:34 - [36mINFO [0m notes_to_pdf.py _run_all:525                           
################################################################################
# Action selected:
################################################################################
      cleanup_before: Yes
    preprocess_notes: Yes
       render_images: Yes
          run_pandoc: Yes
      copy_to_gdrive: -
                open: Yes
       cleanup_after: Yes
21:50:34 - [36mINFO [0m notes_to_pdf.py _run_all:533                           21:50:34 - [36mINFO [0m notes_to_pdf.py _run_all:533                           Logging the actions into a script
21:50:34 hsystem.py _system:211                              > (rm -rf /app/dev_scripts_helpers/documentation/test/outcomes/Test_notes_to_pdf1.test3/tmp.scratch/tmp.notes_to_pdf*) 2>&1
21:50:34 hsystem.py _system:211                              > (find /app \( -path '*/.git' -o -path '*/.mypy_cache' \) -prune -o -name "preprocess_notes.py" -print) 2>&1
21:50:35 hsystem.py _system:211                              > (/app/dev_scripts_helpers/documentation/preprocess_notes.py --input /app/dev_scripts_helpers/documentation/test/outcomes/Test_notes_to_pdf1.test3/tmp.scratch/tmp.notes_to_pdf.filter_by_header.txt --output /app/dev_scripts_helpers/documentation/test/outcomes/Test_notes_to_pdf1.test3/tmp.scratch/tmp.notes_to_pdf.preprocess_notes.txt --type pdf --toc_type none) 2>&1
21:50:36 hsystem.py _system:211                              > (find /app \( -path '*/.git' -o -path '*/.mypy_cache' \) -prune -o -name "render_images.py" -print) 2>&1
21:50:36 hsystem.py _system:211                              > (/app/dev_scripts_helpers/documentation/render_images.py --in_file_name /app/dev_scripts_helpers/documentation/test/outcomes/Test_notes_to_pdf1.test3/tmp.scratch/tmp.notes_to_pdf.preprocess_notes.txt --out_file_name /app/dev_scripts_helpers/documentation/test/outcomes/Test_notes_to_pdf1.test3/tmp.scratch/tmp.notes_to_pdf.render_image.txt) 2>&1
21:50:37 hsystem.py _system:211                              > (uname -m) 2>&1
21:50:37 hsystem.py _system:211                              > (docker image ls --filter reference=tmp.pandoc_texlive.aarch64.8689d816 -q) 2>&1
21:50:37 - [41mERROR[0m hsystem.py _system:260             21:50:37 - [41mERROR[0m hsystem.py _system:260             
################################################################################
cmd='(docker image ls --filter reference=tmp.pandoc_texlive.aarch64.8689d816 -q) 2>&1' failed with rc='1'
################################################################################
Output of the failing command is:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
